services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        platform: linux/amd64
        container_name: stayhub-sqlserver
        
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "StayHub_Dev123!"
            MSSQL_PID: "Developer"
        
        ports:
            - "1433:1433"
        
        volumes:
            - stayhub-sql-data:/var/opt/mssql

volumes:
    stayhub-sql-data:
