services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: pulsehub-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PulseHub_Dev123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - pulsehub-sqlserver-data:/var/opt/mssql

volumes:
  pulsehub-sqlserver-data: